# -*- coding: utf-8 -*-
"""Hierarichal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KKqVqYmsbu_xNKiGhKjRoaTASwLBKR8_
"""

# Commented out IPython magic to ensure Python compatibility.
# Importing Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# %matplotlib inline

from sklearn.preprocessing import normalize
import scipy.cluster.hierarchy as shc

# Loading Data
data = pd.read_csv('/content/Wholesale customers data.csv')
data.head()

dataScaled = normalize(data)
dataScaled = pd.DataFrame(dataScaled, columns= data.columns)
dataScaled.head()

plt.figure(figsize=(16,6))
plt.title("Dendrogram")
dend = shc.dendrogram(shc.linkage(dataScaled, method='complete'))

plt.figure(figsize=(16,6))
plt.title("Dendrogram")
dend = shc.dendrogram(shc.linkage(dataScaled, method='complete'))
plt.axhline(y=1.3, color='r', linestyle='--')

from sklearn.cluster import AgglomerativeClustering
cluster = AgglomerativeClustering(n_clusters=2, metric='euclidean', linkage='complete')  
cluster.fit_predict(dataScaled)

plt.figure(figsize=(5, 5))  
plt.scatter(dataScaled['Milk'], dataScaled['Grocery'], c=cluster.labels_)