# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SDH9HkashcYPTppdGWX20tvIFMueVoYn
"""

x = [55,58,64,68,70,75,80,84]
y = [340,335,410,460,450,610,735,780]
i = 0
N = len(x)

sum_x = sum(x)
sum_y = sum(y)

sq_x = [i ** 2 for i in x]

x_sq = pow(sum_x,2)

sum_xy = 0
for i in range(0,len(x)):
  sum_xy = sum_xy + (x[i] * y[i])

prod_xy = sum_x * sum_y

print("x:", str(x))
print("y:", str(y))
print("square of x:", str(sq_x))
print("x square:", x_sq)
print("sum of xy:", sum_xy)
print("product of sum of x and y:", prod_xy)
print(N)

w1 = round((sum_xy - (prod_xy/N))/(sum(sq_x)-(x_sq/N)),2)

w0 = round((sum_y - (w1 * sum_x))/N, 2)
w0 = float(w0)

import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
def plot_regression_line(x,y,w0,w1):
  plt.scatter(x, y, color = 'blue', marker = 'o', s = 30)
  # print (x)
  # print (w1)
  y_pred = w0 + w1 * np.array(x)
  plt.plot(x, y_pred)
  plt.xlabel('x')
  plt.ylabel('y')
  plt.show()
plot_regression_line(x,y,w0,w1)