# -*- coding: utf-8 -*-
"""LinearRegressionbyML.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yR50kT8woaI1E9NbLSaMRAJihyU-8CpO
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
score_df = pd.read_csv('/content/carprices1.csv')
print(score_df)

score_df.describe()

x = score_df.iloc[:,:].values
y = score_df.iloc[:, 1].values

x = score_df.iloc[:, :1].values
y = score_df.iloc[:, 1].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)
reg = LinearRegression()
reg.fit(x_train, y_train)

y_pred = reg.predict(x_test)
plt.scatter(x_train, y_train, color = "r")
plt.plot(x_test, y_pred, color='b')
plt.show()